const money = value => `₹${Number(value).toLocaleString('en-IN')}`;
async function getCartId() { let id = localStorage.getItem('deviCartId'); if (!id) { const response = await fetch('/api/carts', { method: 'POST' }); id = (await response.json()).id; localStorage.setItem('deviCartId', id); } return id; }
async function cartRequest(path = '', options = {}) { const id = await getCartId(); const response = await fetch(`/api/carts/${id}${path}`, { headers: { 'Content-Type': 'application/json', ...(localStorage.getItem('deviAuth') ? { Authorization: `Bearer ${localStorage.getItem('deviAuth')}` } : {}) }, ...options }); if (response.status === 404) { localStorage.removeItem('deviCartId'); return cartRequest(path, options); } const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Something went wrong'); return data; }
async function addToCart(productId) { try { await cartRequest('/items', { method: 'POST', body: JSON.stringify({ productId, quantity: 1 }) }); const button = document.querySelector(`[data-add-product="${productId}"]`); if (button) { const label = button.textContent; button.textContent = '✓'; setTimeout(() => button.textContent = label, 1000); } } catch (error) { alert(error.message); } }
function updateCartUi(cart) { document.querySelectorAll('[data-cart-count]').forEach(element => { const count = cart.items.reduce((sum, item) => sum + item.quantity, 0); element.textContent = count; element.hidden = count === 0; }); }
function drawerMarkup(cart) { return cart.items.length ? cart.items.map(item => `<article class="drawer-item"><img src="${item.imageUrl}" alt="${item.name}"><div><p>${item.category.toUpperCase()}</p><h3>${item.name}</h3><strong>${money(item.lineTotal)}</strong><div class="drawer-quantity"><button onclick="setDrawerQuantity(${item.id}, ${item.quantity - 1})" aria-label="Decrease quantity">−</button><span>${item.quantity}</span><button onclick="setDrawerQuantity(${item.id}, ${item.quantity + 1})" aria-label="Increase quantity">+</button><button class="text-button" onclick="setDrawerQuantity(${item.id}, 0)">Remove</button></div></div></article>`).join('') : '<div class="drawer-empty"><p>Your cart is empty.</p><a href="collections.html">Explore our collection</a></div>'; }
async function loadProducts() { const container = document.querySelector('.shop-products'); if (!container) return; if (!localStorage.getItem('deviAuth')) { container.innerHTML = '<div class="login-gate"><h2>Sign in to view our collection</h2><p>Create a devi account to see products, prices, ratings and availability.</p><a class="shop-btn" href="account.html">SIGN IN / CREATE ACCOUNT</a></div>'; return; } const response = await fetch('/api/products', { headers: { Authorization: `Bearer ${localStorage.getItem('deviAuth')}` } }); if (!response.ok) return localStorage.removeItem('deviAuth'); const products = await response.json(); container.innerHTML = products.map((product, index) => `<article class="shop-product" data-category="${product.category}"><span class="product-rank">#${index + 1}</span><div class="shop-product-image">${product.label ? `<span class="product-label">${product.label}</span>` : ''}<img src="${product.imageUrl}" alt="${product.name}"><button class="quick-cart" data-add-product="${product.id}" onclick="addToCart(${product.id})" aria-label="Add ${product.name} to cart">🛒</button></div><div class="shop-product-info"><p>${product.category.toUpperCase()}</p><h3>${product.name}</h3><small>${product.rating ? `★ ${product.rating} (${product.reviewCount})` : 'No reviews yet'} · ${product.stock} in stock</small><strong>${money(product.price)}</strong></div></article>`).join(''); }
async function loadFeaturedProducts() { const container = document.querySelector('.product-container[data-featured]'); if (!container || !localStorage.getItem('deviAuth')) return; const response = await fetch('/api/products', { headers: { Authorization: `Bearer ${localStorage.getItem('deviAuth')}` } }); if (!response.ok) return; const products = await response.json(); container.innerHTML = products.filter(product => product.featured).map(product => `<article class="product-card"><div class="product-image">${product.label ? `<span class="badge">${product.label}</span>` : ''}<img src="${product.imageUrl}" alt="${product.name}"><button class="product-add" data-add-product="${product.id}" onclick="addToCart(${product.id})">Add to cart</button></div><div class="product-details"><p>${product.category.toUpperCase()}</p><h3>${product.name}</h3><small>${product.description}</small><h4>${money(product.price)}</h4></div></article>`).join(''); }
function filterProducts(category, event) { document.querySelectorAll('.filter-btn').forEach(button => button.classList.remove('active')); event.currentTarget.classList.add('active'); document.querySelectorAll('.shop-product').forEach(product => product.hidden = category !== 'all' && product.dataset.category !== category); }
async function openCart() { const panel = document.getElementById('cartPanel'); if (!panel) return location.assign('CART.HTML'); panel.classList.add('open'); const current = await cartRequest(); document.getElementById('cartItems').innerHTML = drawerMarkup(current); document.getElementById('cartTotal').textContent = money(current.total); updateCartUi(current); }
function closeCart() { document.getElementById('cartPanel')?.classList.remove('open'); }
async function setDrawerQuantity(productId, quantity) { try { const current = await cartRequest(`/items/${productId}`, { method: 'PATCH', body: JSON.stringify({ quantity }) }); document.getElementById('cartItems').innerHTML = drawerMarkup(current); document.getElementById('cartTotal').textContent = money(current.total); updateCartUi(current); } catch (error) { alert(error.message); } }
async function checkout() { try { const addressId = Number(document.getElementById('delivery-address')?.value); if (!addressId) return location.assign('account.html'); const order = await cartRequest('/checkout', { method: 'POST', body: JSON.stringify({ addressId }) }); alert(`Thank you for shopping with devi JEWELS! Order reference: ${order.orderId.slice(0, 8).toUpperCase()}.`); closeCart(); } catch (error) { alert(error.message); } }
async function renderCartPage() { const container = document.getElementById('cart-container'); if (!container) return; try { const current = await cartRequest(); container.innerHTML = current.items.length ? current.items.map(item => `<article class="cart-product"><img src="${item.imageUrl}" alt="${item.name}"><div class="cart-product-info"><p class="brand">${item.category.toUpperCase()}</p><h3>${item.name}</h3><p class="product-price">${money(item.price)}</p><p class="stock-note">${item.stock} available</p><div class="quantity-box"><button onclick="setQuantity(${item.id}, ${item.quantity - 1})" aria-label="Decrease quantity">−</button><span>${item.quantity}</span><button onclick="setQuantity(${item.id}, ${item.quantity + 1})" aria-label="Increase quantity">+</button></div><p class="item-total">Item total: <strong>${money(item.lineTotal)}</strong></p></div><button class="remove-product" onclick="setQuantity(${item.id}, 0)" aria-label="Remove ${item.name}">×</button></article>`).join('') : '<div class="empty-cart"><h2>Your shopping bag is empty</h2><p>Add some beautiful pieces to your bag.</p><a class="shop-btn" href="collections.html">SHOP COLLECTION</a></div>'; document.getElementById('cart-subtotal').textContent = money(current.subtotal); document.getElementById('cart-total').textContent = money(current.total); document.getElementById('cart-discount').textContent = `− ${money(current.discount)}`; } catch (error) { container.textContent = error.message; } }
async function applyCoupon() { try { const code = document.getElementById('coupon-code').value; await cartRequest('/coupon', { method: 'POST', body: JSON.stringify({ code }) }); renderCartPage(); } catch (error) { alert(error.message); } }
async function loadAddressesForCheckout() { const select = document.getElementById('delivery-address'); if (!select || !localStorage.getItem('deviAuth')) return; try { const response = await fetch('/api/addresses', { headers: { Authorization: `Bearer ${localStorage.getItem('deviAuth')}` } }); const addresses = await response.json(); select.innerHTML = addresses.length ? addresses.map(address => `<option value="${address.id}">${address.full_name} — ${address.line1}, ${address.city}</option>`).join('') : '<option value="">Add an address in My Account</option>'; } catch {} }
async function setQuantity(productId, quantity) { try { const current = await cartRequest(`/items/${productId}`, { method: 'PATCH', body: JSON.stringify({ quantity }) }); updateCartUi(current); await renderCartPage(); } catch (error) { alert(error.message); } }
async function checkoutFromPage() { await checkout(); await renderCartPage(); }
document.addEventListener('DOMContentLoaded', async () => { loadProducts(); loadFeaturedProducts(); renderCartPage(); loadAddressesForCheckout(); try { updateCartUi(await cartRequest()); } catch { /* Cart will be created on the next interaction. */ } });
