const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const { DatabaseSync } = require('node:sqlite');
const { randomUUID, scryptSync, timingSafeEqual } = require('node:crypto');
const root = __dirname, uploadDir = path.join(root, 'images', 'uploads');
fs.mkdirSync(uploadDir, { recursive: true });
const db = new DatabaseSync(path.join(root, 'devi.db'));
const hash = value => scryptSync(value, 'devi-jewels', 64).toString('hex');
const same = (value, saved) => timingSafeEqual(Buffer.from(hash(value), 'hex'), Buffer.from(saved, 'hex'));
db.exec(`PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS products (id INTEGER PRIMARY KEY,name TEXT NOT NULL UNIQUE,category TEXT NOT NULL,price INTEGER NOT NULL,image_url TEXT NOT NULL,label TEXT,featured INTEGER NOT NULL DEFAULT 0,description TEXT NOT NULL DEFAULT '',stock INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS carts (id TEXT PRIMARY KEY,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,coupon_code TEXT);
CREATE TABLE IF NOT EXISTS cart_items (cart_id TEXT NOT NULL REFERENCES carts(id) ON DELETE CASCADE,product_id INTEGER NOT NULL REFERENCES products(id),quantity INTEGER NOT NULL CHECK(quantity>0),PRIMARY KEY(cart_id,product_id));
CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY,cart_id TEXT NOT NULL,user_id INTEGER,address_id INTEGER,coupon_code TEXT,total INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS order_items (order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id INTEGER NOT NULL,product_name TEXT NOT NULL,price INTEGER NOT NULL,quantity INTEGER NOT NULL,PRIMARY KEY(order_id,product_id));
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'customer',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS addresses (id INTEGER PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,full_name TEXT NOT NULL,phone TEXT NOT NULL,line1 TEXT NOT NULL,line2 TEXT,city TEXT NOT NULL,state TEXT NOT NULL,postal_code TEXT NOT NULL,is_default INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS reviews (id INTEGER PRIMARY KEY,product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5),comment TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(product_id,user_id));
CREATE TABLE IF NOT EXISTS coupons (code TEXT PRIMARY KEY,type TEXT NOT NULL,amount INTEGER NOT NULL,min_order INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,expires_at TEXT);`);
db.exec(`CREATE TABLE IF NOT EXISTS admin_otps (id TEXT PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,code_hash TEXT NOT NULL,expires_at INTEGER NOT NULL,used INTEGER NOT NULL DEFAULT 0);`);
for (const q of ["ALTER TABLE products ADD COLUMN description TEXT NOT NULL DEFAULT ''",'ALTER TABLE products ADD COLUMN stock INTEGER NOT NULL DEFAULT 0','ALTER TABLE carts ADD COLUMN coupon_code TEXT','ALTER TABLE orders ADD COLUMN user_id INTEGER','ALTER TABLE orders ADD COLUMN address_id INTEGER','ALTER TABLE orders ADD COLUMN coupon_code TEXT']) try { db.exec(q); } catch {}
const seeds=[['Eternal Solitaire Ring','rings',4999,'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=85','NEW',1,'A radiant solitaire ring made to celebrate your brightest moments.',12],['Golden Grace Necklace','necklaces',6499,'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=85',null,1,'A graceful gold-toned necklace for everyday elegance.',9],['Celeste Drop Earrings','earrings',3499,'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=85','POPULAR',1,'Delicate drop earrings with a luminous finish.',18],['Royal Gold Bracelet','bracelets',5499,'https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=800&q=85',null,0,'A refined gold-finish statement bracelet.',7],['Aurora Diamond Ring','rings',7999,'https://images.unsplash.com/photo-1627293509201-cd0c5d4e1d16?auto=format&fit=crop&w=800&q=85',null,0,'A sparkling ring for unforgettable occasions.',5],['Pearl Elegance Necklace','necklaces',5999,'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=800&q=85','NEW',0,'A timeless pearl-inspired necklace.',11]];
const seed=db.prepare('INSERT OR IGNORE INTO products (name,category,price,image_url,label,featured,description,stock) VALUES (?,?,?,?,?,?,?,?)');seeds.forEach(row=>seed.run(...row));
const refreshSeed=db.prepare("UPDATE products SET description=?,stock=? WHERE name=? AND (description='' OR stock=0)");seeds.forEach(row=>refreshSeed.run(row[6],row[7],row[0]));
db.prepare("INSERT OR IGNORE INTO users (name,email,password_hash,role) VALUES (?,?,?,'admin')").run('devi Admin','admin@devi.local',hash('deviAdmin2026!'));
db.prepare("INSERT OR IGNORE INTO coupons (code,type,amount,min_order,active) VALUES ('WELCOME10','percent',10,2000,1)").run();
const send=(res,status,value)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(value));};
const body=req=>new Promise((resolve,reject)=>{let text='';req.on('data',c=>{text+=c;if(text.length>6000000)req.destroy();});req.on('end',()=>{try{resolve(text?JSON.parse(text):{});}catch{reject(Error('Invalid JSON'));}});});
const auth=req=>{const token=(req.headers.authorization||'').replace('Bearer ','');return token&&db.prepare('SELECT u.id,u.name,u.email,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=?').get(token);};
const required=(req,res,admin=false)=>{const u=auth(req);if(!u||(admin&&u.role!=='admin')){send(res,401,{error:admin?'Administrator access is required':'Please sign in first'});return null;}return u;};
const productSelect=`SELECT p.id,p.name,p.category,p.price,p.image_url imageUrl,p.label,p.featured,p.description,p.stock,ROUND(AVG(r.rating),1) rating,COUNT(r.id) reviewCount FROM products p LEFT JOIN reviews r ON r.product_id=p.id GROUP BY p.id`;
const exists=id=>Boolean(db.prepare('SELECT 1 FROM carts WHERE id=?').get(id));
function cart(id){const items=db.prepare('SELECT p.id,p.name,p.category,p.price,p.image_url imageUrl,p.stock,ci.quantity,p.price*ci.quantity lineTotal FROM cart_items ci JOIN products p ON p.id=ci.product_id WHERE ci.cart_id=?').all(id);const subtotal=items.reduce((n,x)=>n+x.lineTotal,0),code=db.prepare('SELECT coupon_code FROM carts WHERE id=?').get(id)?.coupon_code,coupon=code&&db.prepare("SELECT * FROM coupons WHERE code=? AND active=1 AND (expires_at IS NULL OR expires_at>=date('now'))").get(code),discount=coupon&&subtotal>=coupon.min_order?(coupon.type==='percent'?Math.floor(subtotal*coupon.amount/100):coupon.amount):0;return{items,subtotal,discount:Math.min(discount,subtotal),total:subtotal-Math.min(discount,subtotal),coupon:coupon?{code:coupon.code,applied:subtotal>=coupon.min_order}:null};}
function image(data){const m=/^data:image\/(png|jpeg|jpg|webp);base64,(.+)$/.exec(data||'');if(!m)throw Error('Upload a PNG, JPG, or WEBP image');const name=`${randomUUID()}.${m[1]==='jpeg'?'jpg':m[1]}`;fs.writeFileSync(path.join(uploadDir,name),Buffer.from(m[2],'base64'));return`/images/uploads/${name}`;}
async function api(req,res,url){
 if(req.method==='GET'&&url.pathname==='/api/products'){const u=required(req,res);if(!u)return;return send(res,200,db.prepare(`${productSelect} ORDER BY p.id`).all());}
 let m=url.pathname.match(/^\/api\/products\/(\d+)\/reviews$/);if(m&&req.method==='GET')return send(res,200,db.prepare('SELECT r.id,r.rating,r.comment,r.created_at createdAt,u.name FROM reviews r JOIN users u ON u.id=r.user_id WHERE r.product_id=? ORDER BY r.created_at DESC').all(+m[1]));if(m&&req.method==='POST'){const u=required(req,res);if(!u)return;const{rating,comment}=await body(req);if(!Number.isInteger(rating)||rating<1||rating>5||!String(comment||'').trim())return send(res,400,{error:'Choose a rating and write a review'});db.prepare('INSERT INTO reviews (product_id,user_id,rating,comment) VALUES (?,?,?,?) ON CONFLICT(product_id,user_id) DO UPDATE SET rating=excluded.rating,comment=excluded.comment,created_at=CURRENT_TIMESTAMP').run(+m[1],u.id,rating,String(comment).trim());return send(res,201,{ok:true});}
 if(req.method==='POST'&&url.pathname==='/api/auth/register'){const{name,email,password}=await body(req);if(!String(name||'').trim()||!/^\S+@\S+\.\S+$/.test(email||'')||String(password||'').length<8)return send(res,400,{error:'Enter a name, valid email, and password of at least 8 characters'});try{const r=db.prepare('INSERT INTO users (name,email,password_hash) VALUES (?,?,?)').run(name.trim(),email.toLowerCase(),hash(password)),token=randomUUID();db.prepare('INSERT INTO sessions (token,user_id) VALUES (?,?)').run(token,+r.lastInsertRowid);return send(res,201,{token,user:{id:+r.lastInsertRowid,name:name.trim(),email,role:'customer'}});}catch{return send(res,409,{error:'An account already exists with this email'});}}
 if(req.method==='POST'&&url.pathname==='/api/auth/login'){const{email,password}=await body(req),u=db.prepare('SELECT * FROM users WHERE email=?').get(String(email||'').toLowerCase());if(!u||!same(String(password||''),u.password_hash))return send(res,401,{error:'Incorrect email or password'});const token=randomUUID();db.prepare('INSERT INTO sessions (token,user_id) VALUES (?,?)').run(token,u.id);return send(res,200,{token,user:{id:u.id,name:u.name,email:u.email,role:u.role}});}
 if(req.method==='POST'&&url.pathname==='/api/auth/admin-otp/request'){const u=required(req,res,true);if(!u)return;const code=String(Math.floor(100000+Math.random()*900000)),id=randomUUID();db.prepare('INSERT INTO admin_otps (id,user_id,code_hash,expires_at) VALUES (?,?,?,?)').run(id,u.id,hash(code),Date.now()+5*60*1000);console.log(`Admin OTP for ${u.email}: ${code} (valid for 5 minutes)`);return send(res,200,{message:'A one-time code was generated.',developmentCode:code});}
 if(req.method==='POST'&&url.pathname==='/api/auth/admin-otp/verify'){const u=required(req,res,true);if(!u)return;const{code}=await body(req),otp=db.prepare('SELECT * FROM admin_otps WHERE user_id=? AND used=0 AND expires_at>? ORDER BY expires_at DESC LIMIT 1').get(u.id,Date.now());if(!otp||!same(String(code||''),otp.code_hash))return send(res,401,{error:'Incorrect or expired code'});db.prepare('UPDATE admin_otps SET used=1 WHERE id=?').run(otp.id);const unlock=randomUUID();db.prepare('INSERT INTO sessions (token,user_id) VALUES (?,?)').run(unlock,u.id);return send(res,200,{adminToken:unlock});}
 if(req.method==='POST'&&url.pathname==='/api/auth/logout'){db.prepare('DELETE FROM sessions WHERE token=?').run((req.headers.authorization||'').replace('Bearer ',''));return send(res,200,{ok:true});}if(req.method==='GET'&&url.pathname==='/api/me'){const u=required(req,res);if(u)send(res,200,u);return;}
 if(url.pathname==='/api/addresses'){const u=required(req,res);if(!u)return;if(req.method==='GET')return send(res,200,db.prepare('SELECT * FROM addresses WHERE user_id=? ORDER BY is_default DESC,id DESC').all(u.id));if(req.method==='POST'){const a=await body(req);for(const k of['full_name','phone','line1','city','state','postal_code'])if(!String(a[k]||'').trim())return send(res,400,{error:'Please complete all required address fields'});if(a.is_default)db.prepare('UPDATE addresses SET is_default=0 WHERE user_id=?').run(u.id);const r=db.prepare('INSERT INTO addresses (user_id,full_name,phone,line1,line2,city,state,postal_code,is_default) VALUES (?,?,?,?,?,?,?,?,?)').run(u.id,a.full_name,a.phone,a.line1,a.line2||'',a.city,a.state,a.postal_code,a.is_default?1:0);return send(res,201,{id:+r.lastInsertRowid});}}
 if(req.method==='POST'&&url.pathname==='/api/carts'){const id=randomUUID();db.prepare('INSERT INTO carts (id) VALUES (?)').run(id);return send(res,201,{id,...cart(id)});}m=url.pathname.match(/^\/api\/carts\/([\w-]+)$/);if(m&&req.method==='GET')return exists(m[1])?send(res,200,{id:m[1],...cart(m[1])}):send(res,404,{error:'Cart not found'});
 m=url.pathname.match(/^\/api\/carts\/([\w-]+)\/items$/);if(m&&req.method==='POST'){const id=m[1],{productId,quantity=1}=await body(req),p=db.prepare('SELECT stock FROM products WHERE id=?').get(productId),old=db.prepare('SELECT quantity FROM cart_items WHERE cart_id=? AND product_id=?').get(id,productId)?.quantity||0;if(!exists(id)||!p||!Number.isInteger(quantity)||quantity<1||old+quantity>p.stock)return send(res,400,{error:'This item is not available in that quantity'});db.prepare('INSERT INTO cart_items (cart_id,product_id,quantity) VALUES (?,?,?) ON CONFLICT(cart_id,product_id) DO UPDATE SET quantity=quantity+excluded.quantity').run(id,productId,quantity);return send(res,200,{id,...cart(id)});}
 m=url.pathname.match(/^\/api\/carts\/([\w-]+)\/items\/(\d+)$/);if(m&&req.method==='PATCH'){const[id,pid]=[m[1],+m[2]],{quantity}=await body(req),p=db.prepare('SELECT stock FROM products WHERE id=?').get(pid);if(!exists(id)||!p||!Number.isInteger(quantity)||quantity<0||quantity>p.stock)return send(res,400,{error:'Requested quantity is unavailable'});if(quantity)db.prepare('UPDATE cart_items SET quantity=? WHERE cart_id=? AND product_id=?').run(quantity,id,pid);else db.prepare('DELETE FROM cart_items WHERE cart_id=? AND product_id=?').run(id,pid);return send(res,200,{id,...cart(id)});}
 m=url.pathname.match(/^\/api\/carts\/([\w-]+)\/coupon$/);if(m&&req.method==='POST'){const{code}=await body(req),c=db.prepare("SELECT * FROM coupons WHERE code=? AND active=1 AND (expires_at IS NULL OR expires_at>=date('now'))").get(String(code||'').trim().toUpperCase()),current=cart(m[1]);if(!c)return send(res,400,{error:'That coupon is not valid'});if(current.subtotal<c.min_order)return send(res,400,{error:`This coupon needs an order of at least ₹${c.min_order}`});db.prepare('UPDATE carts SET coupon_code=? WHERE id=?').run(c.code,m[1]);return send(res,200,{id:m[1],...cart(m[1])});}
 m=url.pathname.match(/^\/api\/carts\/([\w-]+)\/checkout$/);if(m&&req.method==='POST'){const u=required(req,res);if(!u)return;const{addressId}=await body(req),id=m[1],a=db.prepare('SELECT id FROM addresses WHERE id=? AND user_id=?').get(addressId,u.id),current=cart(id);if(!a)return send(res,400,{error:'Choose a saved delivery address'});if(!current.items.length)return send(res,400,{error:'Your cart is empty'});if(current.items.some(x=>x.quantity>x.stock))return send(res,400,{error:'One or more items are no longer in stock'});const orderId=randomUUID();db.exec('BEGIN');try{db.prepare('INSERT INTO orders (id,cart_id,user_id,address_id,coupon_code,total) VALUES (?,?,?,?,?,?)').run(orderId,id,u.id,a.id,current.coupon?.code||null,current.total);const add=db.prepare('INSERT INTO order_items (order_id,product_id,product_name,price,quantity) VALUES (?,?,?,?,?)'),reduce=db.prepare('UPDATE products SET stock=stock-? WHERE id=?');current.items.forEach(x=>{add.run(orderId,x.id,x.name,x.price,x.quantity);reduce.run(x.quantity,x.id);});db.prepare('DELETE FROM cart_items WHERE cart_id=?').run(id);db.prepare('UPDATE carts SET coupon_code=NULL WHERE id=?').run(id);db.exec('COMMIT');return send(res,201,{orderId,total:current.total});}catch(e){db.exec('ROLLBACK');throw e;}}
 if(url.pathname.startsWith('/api/admin')){const u=required(req,res,true);if(!u)return;if(req.method==='GET'&&url.pathname==='/api/admin/products')return send(res,200,db.prepare(`${productSelect} ORDER BY p.id`).all());if(req.method==='POST'&&url.pathname==='/api/admin/upload'){const{image:raw}=await body(req);return send(res,201,{imageUrl:image(raw)});}if(url.pathname==='/api/admin/products'&&req.method==='POST'){const p=await body(req);if(!p.name||!p.category||!Number.isInteger(p.price)||!Number.isInteger(p.stock)||!p.imageUrl)return send(res,400,{error:'Complete the required product details'});const r=db.prepare('INSERT INTO products (name,category,price,image_url,label,featured,description,stock) VALUES (?,?,?,?,?,?,?,?)').run(p.name,p.category,p.price,p.imageUrl,p.label||null,p.featured?1:0,p.description||'',p.stock);return send(res,201,{id:+r.lastInsertRowid});}m=url.pathname.match(/^\/api\/admin\/products\/(\d+)$/);if(m&&req.method==='PUT'){const p=await body(req);db.prepare('UPDATE products SET name=?,category=?,price=?,image_url=?,label=?,featured=?,description=?,stock=? WHERE id=?').run(p.name,p.category,p.price,p.imageUrl,p.label||null,p.featured?1:0,p.description||'',p.stock,+m[1]);return send(res,200,{ok:true});}if(m&&req.method==='DELETE'){db.prepare('DELETE FROM products WHERE id=?').run(+m[1]);return send(res,200,{ok:true});}if(url.pathname==='/api/admin/coupons'&&req.method==='GET')return send(res,200,db.prepare('SELECT * FROM coupons ORDER BY code').all());if(url.pathname==='/api/admin/coupons'&&req.method==='POST'){const c=await body(req);db.prepare('INSERT INTO coupons (code,type,amount,min_order,active,expires_at) VALUES (?,?,?,?,?,?) ON CONFLICT(code) DO UPDATE SET type=excluded.type,amount=excluded.amount,min_order=excluded.min_order,active=excluded.active,expires_at=excluded.expires_at').run(String(c.code).toUpperCase(),c.type,c.amount,c.minOrder||0,c.active?1:0,c.expiresAt||null);return send(res,201,{ok:true});}}
 return send(res,404,{error:'Route not found'});
}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp'};
http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host}`);if(url.pathname.startsWith('/api/'))return await api(req,res,url);const wanted=url.pathname==='/'?'/index.html':decodeURIComponent(url.pathname),file=path.resolve(root,`.${wanted}`);if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404);return res.end('Not found');}res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream'});res.end(data);});}catch(e){send(res,500,{error:e.message});}}).listen(process.env.PORT||3000,()=>console.log('devi is running at http://localhost:3000'));
